// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-qcuauQSV4UBVJNSDovcB79DrFFo7EDo',
    appId: '1:1029053761989:web:75525c4a409402cceca3ac',
    messagingSenderId: '1029053761989',
    projectId: 'edu-flutter-demo',
    authDomain: 'edu-flutter-demo.firebaseapp.com',
    storageBucket: 'edu-flutter-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMUr7j9GUCslWdZ0mjDuADREF6q-IE4jA',
    appId: '1:1029053761989:android:b046ecdb8d2349d1eca3ac',
    messagingSenderId: '1029053761989',
    projectId: 'edu-flutter-demo',
    storageBucket: 'edu-flutter-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCR8gKibn2gIk1RiTNqBDDQs3-awtG8ik',
    appId: '1:1029053761989:ios:e23ad986352e6a21eca3ac',
    messagingSenderId: '1029053761989',
    projectId: 'edu-flutter-demo',
    storageBucket: 'edu-flutter-demo.appspot.com',
    iosClientId: '1029053761989-ocksfuuno34pr88b9b9flo51jh9s39t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEcommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCR8gKibn2gIk1RiTNqBDDQs3-awtG8ik',
    appId: '1:1029053761989:ios:e23ad986352e6a21eca3ac',
    messagingSenderId: '1029053761989',
    projectId: 'edu-flutter-demo',
    storageBucket: 'edu-flutter-demo.appspot.com',
    iosClientId: '1029053761989-ocksfuuno34pr88b9b9flo51jh9s39t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEcommerceFirebase',
  );
}
